<?php
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'http://localhost:8086/write?db=log_connections');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "cpu_load_short,host=server01,region=us-west value=0.64 1434055562000000000");

    $headers = array();
    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
?>

<html>
    <head></head>
    <body>
        Just one more testing page...
        <script>
            top.postMessage(
                JSON.stringify("open('https://facebook.com');alert('Payload');"),
                "*"              
            );
        </script>
    </body>
</html>